import assert from 'node:assert/strict';
import { readFile, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
const json=async path=>JSON.parse(await readFile(root+path,'utf8'));
const [project,cli,template,lock,templateLock]=await Promise.all(['package.json','packages/create-kumuno/package.json','templates/default/package.json','package-lock.json','templates/default/package-lock.json'].map(json));
assert.equal(project.private,true);
assert.equal(template.private,true);
assert.notEqual(cli.private,true);
assert.equal(cli.name,'create-kumuno');
assert.match(cli.version,/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/);
assert.notEqual(cli.version,'0.0.0');
assert.equal(cli.publishConfig.registry,'https://registry.npmjs.org/');
assert.equal(cli.publishConfig.access,'public');
assert.equal(cli.publishConfig.tag,'next');
assert.equal(cli.repository.url,'git+https://github.com/kumuno-dev/kumuno.git');
assert.equal(cli.repository.directory,'packages/create-kumuno');
assert.equal(cli.bin['create-kumuno'],'src/cli.mjs');
assert.equal(cli.engines.node,'24.x');
assert((await stat(root+'packages/create-kumuno/src/cli.mjs')).mode & 0o111,'CLI must be executable');
const license=await readFile(root+'LICENSE','utf8');
assert(license.startsWith('MIT License\n'));
for(const prefix of ['packages/create-kumuno/','templates/default/'])assert.equal(await readFile(root+prefix+'LICENSE','utf8'),license);
for(const value of [project,cli,template,lock.packages[''],lock.packages['packages/create-kumuno'],templateLock.packages['']])assert.equal(value.license,'MIT');
assert.equal(lock.packages['packages/create-kumuno'].version,cli.version);
assert.equal(templateLock.packages[''].version,template.version);
assert(cli.files.includes('LICENSE'));
console.log(`Release metadata verified: ${cli.name}@${cli.version}, MIT, npm next tag. This check does not publish.`);
